# Generated by Django 3.2 on 2024-02-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoo.diet')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoo.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='diets',
            field=models.ManyToManyField(through='aoo.PatientDiet', to='aoo.Diet'),
        ),
        migrations.CreateModel(
            name='DietItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoo.diet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aoo.item')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='items',
            field=models.ManyToManyField(through='aoo.DietItem', to='aoo.Item'),
        ),
    ]
