# Generated by Django 3.2 on 2024-02-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0002_auto_20240220_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanfood',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
