# Generated by Django 3.2 on 2024-02-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0003_alter_mealplanfood_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_assigned',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aoo.mealplan'),
        ),
    ]
