# Generated by Django 3.2 on 2024-02-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0004_auto_20240220_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='aoo.mealplan'),
        ),
    ]
