# Generated by Django 3.2 on 2024-02-20 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0006_appointments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BMI', models.FloatField(verbose_name='Body Mass Index')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('height', models.FloatField(verbose_name='Height (m)')),
                ('body_fat', models.FloatField(verbose_name='Body Fat (%)')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('RMR', models.FloatField(verbose_name='Resting Metabolic Rate (kcal/day)')),
                ('visceral_fat', models.PositiveIntegerField(verbose_name='Visceral Fat')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_compositions', to='aoo.appointments')),
            ],
        ),
    ]
