# Generated by Django 3.2 on 2024-02-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0007_bodycomposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodycomposition',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointments',
            name='body_composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aoo.bodycomposition'),
        ),
    ]
