# Generated by Django 3.2 on 2024-02-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0008_auto_20240220_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycomposition',
            name='Patient_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Patient Name'),
        ),
    ]
