# Generated by Django 3.2 on 2024-02-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0009_bodycomposition_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Appointment_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Appointment Description'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_assigned',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bodycomposition',
            name='Patient_name',
            field=models.CharField(default='', max_length=100, verbose_name='Patient Name'),
        ),
    ]
