# Generated by Django 3.2 on 2024-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0011_auto_20240220_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanfood',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='mealplanfood',
            name='timing',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], default='', max_length=20, verbose_name='Timing'),
        ),
    ]
