# Generated by Django 3.2 on 2024-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0012_auto_20240220_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplanfood',
            name='short_description',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Short Description'),
        ),
    ]
