# Generated by Django 3.2 on 2024-02-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0014_alter_mealplanfood_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='meal_plans',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='body_composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='aoo.bodycomposition'),
        ),
    ]
