# Generated by Django 3.2 on 2024-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0015_auto_20240220_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AddField(
            model_name='patient',
            name='acidity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='body_pain',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='coffee_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='constipation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='consume_fruits_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='consume_oil_or_ghee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='delivery_type',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='diarrhea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='eat_outside_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='flour_used',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_allergy',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_preference',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='food_taste',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='glass_of_water_glasses',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='glass_of_water_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_children',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='headache',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='irregular_period_details',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_issue',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='milk_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='milk_used',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='noon_nap',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_children',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='oil_or_ghee_brand',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pcos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='purpose',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='regular_periods',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rice_used',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='salt_used',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sleep_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sugar_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='supplement',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tea_consumption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='thyroid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='wake_up_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
