# Generated by Django 3.2 on 2024-02-21 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0016_auto_20240221_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, default=' ', max_length=5, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='noon_nap',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
    ]
