# Generated by Django 3.2 on 2024-02-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0020_alter_patient_food_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodpreference',
            old_name='name',
            new_name='preference',
        ),
        migrations.AlterField(
            model_name='patient',
            name='food_preferences',
            field=models.ManyToManyField(blank=True, related_name='preferences', to='aoo.FoodPreference'),
        ),
    ]
