# Generated by Django 3.2 on 2024-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0022_auto_20240221_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='food_preferences',
            field=models.TextField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='food_taste',
            field=models.TextField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
