# Generated by Django 3.2 on 2024-02-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0023_auto_20240221_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='glass_of_water_glasses',
            new_name='water_glasses',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='glass_of_water_quantity',
        ),
    ]
