# Generated by Django 3.2 on 2024-02-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0024_auto_20240221_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='water_glasses',
        ),
    ]
