# Generated by Django 3.2 on 2024-02-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0027_auto_20240221_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='consume_oil_or_ghee',
        ),
        migrations.AlterField(
            model_name='patient',
            name='consume_fruits_daily',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='eat_outside_food',
            field=models.TextField(default=False),
        ),
    ]
